spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name:
        principal-cookie-name:
        profile-enable:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny:
      aop-patterns: top.gjp0609.webtools
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webtools?useUnicode=true&characterEncoding=UTF-8
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
  thymeleaf:
    cache: false # 关闭缓存
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 9001
    password:
    database: 0
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 3
    template:
      default-topic: topic1
    consumer:
      group-id: 0
    producer:
      batch-size: 1000
  mail:
    host: smtp.***.com
    username: me@***.com
    password:
server:
  port: 8083